version: '2'

networks:
    kafka-cluster-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.98.0.0/16

services:
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        networks:
              kafka-cluster-net:
                  ipv4_address: "172.98.100.2"
        ports:
          - "2181:2181"

    kafka1:
        image: wurstmeister/kafka
        container_name: kafka1
        networks:
                kafka-cluster-net:
                    ipv4_address: "172.98.1.1"
        ports:
          - "9201:9092"
        environment:
          KAFKA_LISTENERS: PLAINTEXT://172.98.1.1:9092
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_BROKER_ID: 1
          # # topic的默认分区数
          # KAFKA_NUM_REPLICATIONS: 2

          # # 复制因子
          # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

          # KAFKA_OFFSETS_TOPIC_NUM_REPLICATION: 2
         
          # # 自动创建topic的默认的副本数
          # KAFKA_DEFAULT_REPLICATION_FACTOR: 3

          # # 同步副本数
          # KAFKA_MIN_INSYNC_REPLICAS: 6

          # # 是否可以自动创建topic
          # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
          
          # # 启用自动平衡leader
          # KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
          JMX_PORT: 9999
        depends_on:
          - zookeeper

    kafka2:
        image: wurstmeister/kafka
        container_name: kafka2
        networks:
                kafka-cluster-net:
                    ipv4_address: "172.98.1.2"
        ports:
          - "9202:9092"
        environment:
          KAFKA_LISTENERS: PLAINTEXT://172.98.1.2:9092
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_BROKER_ID: 2
          JMX_PORT: 9999
        depends_on:
          - zookeeper

    kafka3:
        image: wurstmeister/kafka
        container_name: kafka3
        networks:
                kafka-cluster-net:
                    ipv4_address: "172.98.1.3"
        ports:
          - "9203:9092"
        environment:
          KAFKA_LISTENERS: PLAINTEXT://172.98.1.3:9092
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_BROKER_ID: 3
          JMX_PORT: 9999
        depends_on:
          - zookeeper      

    kafka4:
        image: wurstmeister/kafka
        container_name: kafka4
        networks:
                kafka-cluster-net:
                    ipv4_address: "172.98.1.4"
        ports:
          - "9204:9092"
        environment:
          KAFKA_LISTENERS: PLAINTEXT://172.98.1.4:9092
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_BROKER_ID: 4
          JMX_PORT: 9999
        depends_on:
          - zookeeper

    kafka5:
      image: wurstmeister/kafka
      container_name: kafka5
      networks:
              kafka-cluster-net:
                  ipv4_address: "172.98.1.5"
      ports:
        - "9205:9092"
      environment:
        KAFKA_LISTENERS: PLAINTEXT://172.98.1.5:9092
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_BROKER_ID: 5
        JMX_PORT: 9999
      depends_on:
        - zookeeper      

    kafka-manager:
        image: sheepkiller/kafka-manager
        container_name: kafka-manager
        networks:
          kafka-cluster-net:
              ipv4_address: "172.98.99.1"
        environment:
          ZK_HOSTS: 172.98.100.2:2181
          APPLICATION_SECRET: "letmein"
        ports:
          - "9900:9000"
        depends_on:
          - kafka1
          - kafka2
          - kafka3
          - kafka4
          - kafka5
          - zookeeper