version: '2'

networks:
    kafka-cluster-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.98.0.0/16

services:
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        networks:
              kafka-cluster-net:
                  ipv4_address: "172.98.100.2"
        ports:
          - "2181:2181"

    kafka01:
        image: wurstmeister/kafka
        container_name: kafka1
        networks:
                kafka-cluster-net:
                    ipv4_address: "172.98.1.1"
        ports:
          - "9201:9092"
        environment:
          KAFKA_LISTENERS: PLAINTEXT://172.98.1.1:9201
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_BROKER_ID: 1
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
          - zookeeper

    kafka2:
        image: wurstmeister/kafka
        container_name: kafka2
        networks:
                kafka-cluster-net:
                    ipv4_address: "172.98.1.2"
        ports:
          - "9202:9092"
        environment:
          KAFKA_LISTENERS: PLAINTEXT://172.98.1.2:9202
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_BROKER_ID: 2
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
          - zookeeper

    kafka3:
        image: wurstmeister/kafka
        container_name: kafka3
        networks:
                kafka-cluster-net:
                    ipv4_address: "172.98.1.3"
        ports:
          - "9203:9092"
        environment:
          KAFKA_LISTENERS: PLAINTEXT://172.98.1.3:9202
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_BROKER_ID: 3
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
          - zookeeper      

    kafka-manager:
        image: sheepkiller/kafka-manager
        container_name: kafka-manager
        networks:
          kafka-cluster-net:
              ipv4_address: "172.98.99.1"
        environment:
          ZK_HOSTS: 172.98.100.2:2181
          APPLICATION_SECRET: "letmein"
        ports:
          - "9900:9000"
        depends_on:
          - zookeeper